# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos8"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Web Application server 1.
  config.vm.define "web1" do |app|
    app.vm.hostname = "orc-web1.test"
    app.vm.network :private_network, ip: "192.168.60.10"
  end

  # Web Application server 2.
  config.vm.define "web2" do |app|
    app.vm.hostname = "orc-web2.test"
    app.vm.network :private_network, ip: "192.168.60.11"
  end
  
  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook-install-apache.yml"

    ansible.groups = {
      "web" => ["web[1:2]"]
    }
  end

  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook-install-and-run-nodejs.yml"

    ansible.groups = {
      "web" => ["web[1:2]"]
    }
  end
end